### PR TITLE
Stub doc-tree -> doc-gen stage

### LINKED ISSUE #6: "Stub" a pipeline for application's "flow"
Super rough outline:

image

Broad strokes: 

**Launch stage**

```
Config module :: Config.{toml,yaml,etc} -> Config struct
```

**Parsing stage**

```
DocTree module :: rustc_ast -> DocTree
```

**Generation stage**

```
Generator module :: DocTree -> "Insertion Records"
```

**Source code stage**

```
Insertion Layer :: InsertionRecords -> Checks source code for conformity / Ensures doc comment exists
Insertion Layer :: InsertionRecords -> Reconcile (merge/complete) doc comments
```

### PR DESCRIPTION
**Pull request by connorkuehl**

### CODE REVIEW

**Comment by connorkuehl** [comment]
Actually, I think I'll need to update this to take a `DocConfig` as well.﻿

**Comment by nordzilla** [comment]
> Actually, I think I'll need to update this to take a `DocConfig` as well.

Yeah, this is mostly why I only created modules and no concrete structs. But I'm fine with having simple stubs for now.

**Review by nordzilla — APPROVED** [review]
Looks good to me!

Though I do like to have an issue associated with all todo!() items.

Do you think you could link (and create if needed) issues for these todos?

**Comment by connorkuehl** [comment]
> Looks good to me!
>
> Though I do like to have an issue associated with all todo!() items.
>
> Do you think you could link (and create if needed) issues for these
> todos?

Of course! Do you want a link to them in the comments of the source code
or do you mean link to them from this PR?

**Comment by nordzilla** [comment]
> Looks good to me! Though I do like to have an issue associated with all todo!() items. Do you think you could link (and create if needed) issues for these todos?
> Of course! Do you want a link to them in the comments of the source code or do you mean link to them from this PR?


I just mean in the source code, as in
 ```rust
 todo!("#7 - do the thing!")`
 ```
 or
 ```rust
 // TODO(#7) do the thing!
 ```

**Pull request merged**
