### PR TITLE
Add initial cli

### LINKED ISSUE #18: Implement CLI
We need to have a way to handle command-line arguments when people invoke cargo doc-gen. 

We should probably use [clap](https://crates.io/crates/clap) to implement this. 

Initial Features:
- `cargo doc-gen` Runs the main application 
- `cargo doc-gen --help` Displays the help menu
- `cargo doc-gen -c|--check`  Validates the existing documentation
- `cargo doc-gen -t|--threads{num-threads}` Sets the number of threads that should be used

### PR DESCRIPTION
**Pull request by connorkuehl**
Closes #18 

```console
$ cargo doc-gen --help
cargo-doc-gen 0.1.0
Erik Nordin <nordzillacode@gmail.com>, Caleb Boylan <calebboylan@gmail.com>, Connor Kuehl <cipkuehl@gmail.com>


USAGE:
    cargo-doc-gen [FLAGS] [OPTIONS]

FLAGS:
    -c, --check      Validate existing documentation
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -t, --threads <threads>    Maximum number of threads to use
```

```console
$ cargo doc-gen -t0
error: Invalid value for '--threads <threads>': Number of threads must be greater than zero
```

### CODE REVIEW

**Comment by squidboylan** [comment]
I wouldnt bother showing author info but other than that it looks good to me

**Review by nordzilla — APPROVED** [review]
> I wouldnt bother showing author info but other than that it looks good to me

Looks good to me as well! Thanks for setting up the initial CLI! :)

I don't have a strong preference either way about the authors. I think I usually leave them out myself, because I figure people can go look it up if they care. 

I think I'd like to explore using [thiserror](https://crates.io/crates/thiserror) in this project, but that's certainly something we can explore later. The static strings are certainly fine right now.

**Comment by connorkuehl** [comment]
Thanks! I didn’t want to get too opinionated about error handling. I was just stubbing out the entry point for the application and wrapping it with simple error reporting. In the cli module I used a String as the error type because the validator closure expects the error type to be a string iirc

**Comment by nordzilla** [comment]
> In the cli module I used a String as the error type because the validator closure expects the error type to be a string iirc

Totally, though I'm pretty sure `thiserror` implements `Display` for error types so that you can call `to_string()` on them. But as I said, that's something we can look into later when we actually need error handling in the program logic.

**Pull request merged**
